Repository deckhouse/dmt, pull requests merged in 2025-09, with the labels that each got.

#256 [dmt] remove volume mounts check
  pkg/linters/container/rules/container_check_read_only_root_filesystem.go
Labels: bug

#260 [trdl] bump channel versions to 0.1.35 in trdl_channels.yaml
  trdl_channels.yaml
Labels: trdl

#264 [dmt ]Configuration Architecture Overhaul (feature-flags as a warn level rules)
  internal/manager/manager.go
  internal/metrics/metrics.go
  internal/metrics/metrics_test.go
  internal/module/module.go
  pkg/config.go
  pkg/config/config.go
  pkg/config/global/global.go
  pkg/config/linters_settings.go
  pkg/config/loader.go
  pkg/linters/container/container.go
  pkg/linters/container/container_test.go
  pkg/linters/container/rules.go
  pkg/linters/container/rules_test.go
  pkg/linters/hooks/hooks.go
  pkg/linters/hooks/rules/rules.go
  pkg/linters/images/images.go
  pkg/linters/images/rules/distroless.go
  pkg/linters/images/rules/image.go
  pkg/linters/module/module.go
  pkg/linters/no-cyrillic/no_cyrillic.go
  pkg/linters/openapi/openapi.go
  pkg/linters/openapi/rules/crds.go
  pkg/linters/openapi/rules/crds_test.go
  pkg/linters/openapi/rules/enum.go
  pkg/linters/openapi/rules/enum_test.go
  pkg/linters/openapi/rules/ha.go
  pkg/linters/openapi/rules/keys.go
  pkg/linters/openapi/rules/keys_test.go
  pkg/linters/rbac/rbac.go
  pkg/linters/templates/rules/grafana.go
  pkg/linters/templates/rules/prometheus_rules.go
  pkg/linters/templates/templates.go
Labels: enhancement
